<div class="page">
	<div class="content_header border_box">
		<span class="latest_news vertical_center"> Refund Policy</span>
	</div>

    <div class="page-body border_box self_clear">
		<h2>AGREEMENT</h2>
		

		<p> WE ACCEPT ALL YOUR CONTRIBUTIONS ONLY IF YOU WISH TO HELP <b>SHAIYA Duff</b>. WE AWARD YOU WITH SHAIYA POINTS (<b>SP</b>) THAT CAN BE USED TO PURCHASE GOODS IN THE GAME STORE OR TO RECEIVE ADDITIONAL SERVICES.</p>

		<p><br />SHAIYA POINTS (<b>SP</b>) CANNOT BE EXCHANGED BACK INTO A CURRENCY. PURCHASES OF <b>SP</b> SETS ARE NOT REFUNDABLE.</p>
		<p><br />IF A VIRTUAL ITEM CONTAINS FAULTS ON RECEIVING, YOU SHOULD INFORM <b>SHAIYA Duff</b> IMMEDIATELY AND MUST INFORM US WITHIN 24 HOURS OF RECEIVING IN ORDER TO RECEIVE <b>SP</b> BACK EQUAL TO THE PURCHASE PRICE OF THE RELEVANT VIRTUAL ITEM. ANY NOTIFICATION RECEIVED OUTSIDE OF THIS TIME PERIOD IS AT THE EXCLUSIVE DISCRETION OF <b>SHAIYA Duff</b> MANAGEMENT.</p>
		<p><br />ACCIDENTAL PURCHASES OF <b>SP</b> OCCURRED AS A RESULT OF TECHNICAL FAULT IN THE PAYMENT SYSTEM YOU PAID THROUGH MUST BE DI<b>SP</b>UTED WITH THE RE<b>SP</b>ECTIVE PAYMENT PROCESSOR. <b>SHAIYA Duff</b> IS NOT RE<b>SP</b>ONSIBLE FOR ANY TECHNICAL FAULTS ARISING AT PAYMENT PROCESSORS. <b>SHAIYA Duff</b> IS NOT IN CHARGE OF HANDLING CREDIT/DEBIT AND BANK TRANSACTIONS UNDERTAKEN TO PURCHASE <b>SP</b>.</p>
		<p><br />WHERE ANY REFUND IS ISSUED UNDER ANY CIRCUMSTANCES, <b>SHAIYA Duff</b> RESERVES THE RIGHT TO SU<b>SP</b>END OR TERMINATE THE RE<b>SP</b>ECTIVE ACCOUNT WITH THE WEBSITE.</p>
		<p><br />FOR ALL ENQUIRIES ABOUT THE STATUS OF YOUR ORDERS, PLEASE <a href="./?p=contact">CONTACT US</a>!</p>
		
			
    </div>
</div>