<div class="page">
	<div class="content_header border_box">
		<span class="latest_news vertical_center"> <a>Terms of Service</a></span>
	</div>

    <div class="page-body border_box self_clear">
		<p><strong>TERMS OF USE</strong><br />BY ACCESSING OR USING <span style="color:orange">WWW.SHAIYA DUFF.COM</span> (THE "SITE") AND ITS SERVICES (THE "SERVICES"), YOU (THE "USER") AGREE TO COMPLY WITH THE TERMS AND CONDITIONS 
		GOVERNING THE USER'S USE OF ANY AREAS OF THE SITE AND AFFILIATED SERVICES AS SET FORTH BELOW.<br /> <br />

		<strong>USE OF SITE</strong><br />THIS SITE OR ANY PORTION OF THE SITE AS WELL AS THE 
		SERVICES MAY NOT BE REPRODUCED, DUPLICATED, COPIED, SOLD, RESOLD, OR OTHERWISE EXPLOITED FOR ANY COMMERCIAL PURPOSE EXCEPT AS EXPRESSLY PERMITTED BY <span style="color:orange">WWW.SHAIYA DUFF.COM</span>. 
		<b>SHAIYA DUFF!</b> RESERVES THE RIGHT TO REFUSE SERVICE IN ITS DISCRETION, WITHOUT LIMITATION, IF <b>SHAIYA DUFF!</b> BELIEVES THE USER CONDUCT VIOLATES APPLICABLE LAW OR IS HARMFUL TO THE 
		INTERESTS OF <b>SHAIYA DUFF!</b>, OTHER USERS OF THE SITE AND THE SERVICES OR ITS AFFILIATES.<br /> <br />

		<strong>USE OF SERVICES</strong><br /><span style="color:orange">WWW.SHAIYA DUFF.COM</span> IS A NON-PROFIT PROJECT DEVELOPED TO 
		IMITATE OUTDATED GAME VERSIONS FOR EDUCATIONAL PURPOSES ONLY. THE SITE AND THE SERVICES DO NOT SUPPORT AND DO NOT PROVIDE ANY MODIFICATION TO GAME FILES. 
		BY USING THE SITE OR THE SERVICES, THE USER AGREES TO TAKE RESPONSIBILITY TO FOLLOW GAME&rsquo;S EULA.<br /> <br />

		

		<strong>SITE ACCOUNT</strong><br />THE USER MAY REGISTER A REGULAR 
		ACCOUNT AND PASSWORD FOR THE SERVICE FOR FREE. YOU ARE RESPONSIBLE FOR ALL ACTIVITY UNDER YOUR ACCOUNT, ASSOCIATED ACCOUNTS, AND PASSWORDS. 
		THE SITE IS NOT RESPONSIBLE FOR UNAUTHORISED ACCESS TO YOUR ACCOUNT, AND ANY LOSS OF VIRTUAL ITEMS ASSOCIATED WITH IT.<br /> <br />

		<strong>EVENTS, VIDEOS AND COMMUNITY CREATIONS</strong><br />UPON REGISTERING AN ACCOUNT, YOU AGREE THAT YOUR ACCOUNT OR CHARACTERS MAY BE INCLUDED IN ANY EVENTS, 
		STREAMS OR VIDEOS FOR PROMOTION OR REVIEW PURPOSES.<br /> <br />

		<strong>ACCESS TO THE SITE AND SERVICES</strong><br /><b>SHAIYA DUFF!</b> PROVIDES FREE AND UNLIMITED ACCESS TO THE SITE AND THE SERVICES.<br /> <br />

		<strong>SUBMISSION</strong><br /><b>SHAIYA DUFF!</b> DOES NOT ASSUME 
		ANY OBLIGATION WITH RESPECT TO ANY SUBMISSION AND NO CONFIDENTIAL OR FIDUCIARY UNDERSTANDING OR RELATIONSHIP IS ESTABLISHED BY THE SITE'S RECEIPT OR ACCEPTANCE OF ANY SUBMISSION. 
		ALL SUBMISSIONS BECOME THE EXCLUSIVE PROPERTY OF THE SITE AND ITS AFFILIATES. THE SITE AND ITS AFFILIATES MAY USE ANY SUBMISSION WITHOUT RESTRICTION AND THE USER SHALL NOT BE ENTITLED 
		TO ANY COMPENSATION.<br /> <br />

		<strong>THIRD-PARTY CONTENT</strong><br />NEITHER <b>SHAIYA DUFF!</b>, NOR ITS AFFILIATES, NOR ANY OF THEIR RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS, NOR ANY 
		THIRD PARTY, INCLUDING ANY PROVIDER/AFFILIATE, OR ANY OTHER USER OF THE SITE AND SERVICES, GUARANTEES THE ACCURACY, COMPLETENESS, OR USEFULNESS OF ANY CONTENT, NOR ITS MERCHANTABILITY 
		OR FITNESS FOR ANY PARTICULAR PURPOSE. IN SOME INSTANCES, THE CONTENT AVAILABLE THROUGH THE SITE MAY REPRESENT THE OPINIONS AND JUDGMENTS OF PROVIDERS/AFFILIATES OR USERS. 
		<b>SHAIYA DUFF!</b> AND ITS AFFILIATES DO NOT ENDORSE AND SHALL NOT BE RESPONSIBLE FOR THE ACCURACY OR RELIABILITY OF ANY OPINION, ADVICE, OR STATEMENT MADE ON THE SITE AND THE 
		SERVICES BY ANYONE OTHER THAN AUTHORISED <b>SHAIYA DUFF!</b> EMPLOYEES. UNDER NO CIRCUMSTANCES SHALL <b>SHAIYA DUFF!</b>, OR ITS AFFILIATES, OR ANY OF THEIR RESPECTIVE OFFICERS, DIRECTORS, 
		EMPLOYEES, OR AGENTS BE LIABLE FOR ANY LOSS, DAMAGE OR HARM CAUSED BY A USER'S RELIANCE ON INFORMATION OBTAINED THROUGH THE SITE AND THE SERVICES. 
		IT IS THE RESPONSIBILITY OF THE USER TO EVALUATE THE INFORMATION, OPINION, ADVICE, OR OTHER CONTENT AVAILABLE THROUGH THIS SITE.<br /> <br />

		<strong>DISCLAIMERS AND LIMITATION OF LIABILITY</strong><br />USER AGREES THAT USE OF THE SITE AND THE SERVICES IS AT THE USER'S SOLE RISK. NEITHER <b>SHAIYA DUFF!</b>, NOR ITS AFFILIATES, 
		NOR ANY OF THEIR RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, THIRD-PARTY CONTENT PROVIDERS, MERCHANTS, SPONSORS, LICENSORS OR THE LIKE (COLLECTIVELY, "PROVIDERS"), 
		WARRANT THAT THE SITE AND THE SERVICES WILL BE UNINTERRUPTED OR ERROR-FREE; NOR DO THEY MAKE ANY WARRANTY AS TO THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SITE AND THE SERVICES,
		 OR AS TO THE ACCURACY, RELIABILITY, OR CURRENCY OF ANY INFORMATION CONTENT, SERVICE, OR MERCHANDISE PROVIDED THROUGH THIS SITE. THE SITE AND THE SERVICES ARE PROVIDED BY <b>SHAIYA DUFF!</b> 
		 ON AN "AS IS" AND "AS AVAILABLE" BASIS. THE SITE MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, AS TO THE OPERATION OF THE SITE, THE INFORMATION, CONTENT, 
		 MATERIALS OR PRODUCTS, INCLUDED ON THIS SITE. TO THE FULL EXTENT PERMISSIBLE BY APPLICABLE LAW, THE SITE DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO, 
		 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. <b>SHAIYA DUFF!</b> WILL NOT BE LIABLE FOR ANY DAMAGES OF ANY KIND ARISING FROM THE USE OF THE SITE AND THE SERVICES, 
		 INCLUDING BUT NOT LIMITED TO DIRECT, INDIRECT, INCIDENTAL, PUNITIVE AND CONSEQUENTIAL DAMAGES. UNDER NO CIRCUMSTANCES SHALL <b>SHAIYA DUFF!</b> OR ANY OTHER PARTY INVOLVED IN CREATING, PRODUCING, 
		 OR DISTRIBUTING THE SITE AND THE SERVICES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES THAT RESULT FROM THE USE OF OR INABILITY TO USE THE SITE AND 
		 THE SERVICES, INCLUDING BUT NOT LIMITED TO RELIANCE BY THE USER ON ANY INFORMATION OBTAINED FROM THE SITE OR THAT RESULT FROM MISTAKES, OMISSIONS, INTERRUPTIONS, DELETION OF FILES OR 
		 EMAIL, ERRORS, DEFECTS, VIRUSES, DELAYS IN OPERATION OR TRANSMISSION, OR ANY FAILURE OF PERFORMANCE, WHETHER OR NOT RESULTING FROM ACTS OF GOD, COMMUNICATIONS FAILURE, THEFT, DESTRUCTION, 
		 OR UNAUTHORISED ACCESS TO THE SITE'S RECORDS, PROGRAMS, OR SERVICES. THE USER HEREBY ACKNOWLEDGES THAT THESE DISCLAIMERS AND LIMITATION ON LIABILITY SHALL APPLY TO ALL CONTENT, 
		 MERCHANDISE, AND SERVICES AVAILABLE THROUGH THE SITE AND THE SERVICES. IN STATES THAT DO NOT ALLOW THE EXCLUSION OF LIMITATION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL 
		 DAMAGES, THE USER AGREES THAT LIABILITY IN SUCH STATES SHALL BE LIMITED TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW.<br /> <br />
		 
		 <strong>TERMINATION OF SERVICE</strong><br /><b>SHAIYA DUFF!</b> RESERVES THE 
		 RIGHT, IN ITS SOLE DISCRETION, TO CHANGE, SUSPEND, LIMIT, OR DISCONTINUE ANY ASPECT OF THE SERVICE AND THE SERVICES AT ANY TIME. <b>SHAIYA DUFF!</b> MAY SUSPEND OR TERMINATE ANY USER'S ACCESS 
		 TO ALL OR PART OF THE SITE AND THE SERVICES, WITHOUT NOTICE, FOR ANY CONDUCT THAT <b>SHAIYA DUFF!</b>, IN ITS SOLE DISCRETION, BELIEVES IS IN VIOLATION OF THESE TERMS AND CONDITIONS.
		 <br /> <br />
		 
		 <strong>DONATIONS</strong><br />DONATIONS ARE MADE ON A VOLUNTARY BASIS IN APPRECIATION OF THE SITE AND THE SERVICES. <b>SHAIYA DUFF!</b> DOES NOT ASSUME ANY FINANCIAL OBLIGATION WITH RESPECT TO DONATIONS. 
		 THE USER MUST BE OVER 18 TO BE ELIGIBLE TO MAKE A DONATION TO <b>SHAIYA DUFF!</b>. <b>SHAIYA DUFF!</b> IS NOT LIABLE FOR ANY UNAUTHORIZED DONATIONS. SP CANNOT BE EXCHANGED BACK INTO A CURRENCY. DONATIONS ARE NOT REFUNDABLE. 
		 <br />		 <br />
		 
		 <strong>ACKNOWLEDGEMENT</strong><br />
		 BY ACCESSING OR USING THE SITE AND THE SERVICES, THE USER AGREES TO BE BOUND BY THESE TERMS AND CONDITIONS, INCLUDING DISCLAIMERS. <b>SHAIYA DUFF!</b> RESERVES THE RIGHT TO MAKE 
		 CHANGES TO THE SITE AND THESE TERMS AND CONDITIONS, INCLUDING DISCLAIMERS, AT ANY TIME. IF YOU DO NOT AGREE TO THE PROVISIONS OF THIS AGREEMENT OR ARE NOT SATISFIED WITH THE SERVICE, 
		 YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE YOUR USE OF THE SERVICE.<br /> <br />
		 
		 <strong>PRIVACY STATEMENT</strong><br />CERTAIN USER INFORMATION COLLECTED THROUGH THE USE OF THIS WEBSITE IS 
		 AUTOMATICALLY STORED FOR REFERENCE. WE TRACK SUCH INFORMATION TO PERFORM INTERNAL RESEARCH ON OUR USERS' DEMOGRAPHIC INTERESTS AND BEHAVIOUR AND TO BETTER UNDERSTAND, PROTECT AND SERVE 
		 OUR COMMUNITY OF USERS. PAYMENT OR ANY OTHER FINANCIAL INFORMATION IS NEVER SUBMITTED, DISCLOSED OR STORED ON THE SITE AND IS BOUND TO TERMS AND CONDITIONS AND PRIVACY POLICY OF OUR 
		 RESPECTIVE PARTNERS AND/OR PAYMENT PROCESSORS. BASIC USER INFORMATION (SUCH AS IP ADDRESS, LOGS FOR USING WEBSITE INTERFACE AND ACCOUNT MANAGEMENT) MAY BE DISCLOSED TO OUR PARTNERS IN 
		 MUTUAL EFFORTS TO COUNTER POTENTIAL ILLEGAL ACTIVITIES. <b>SHAIYA DUFF!</b> MAKES SIGNIFICANT EFFORT TO PROTECT SUBMITTED INFORMATION TO PREVENT UNAUTHORISED ACCESS TO THAT INFORMATION IN ITS 
		 INTERNAL PROCEDURES AND TECHNOLOGY. HOWEVER, WE DO NOT GUARANTEE, NOR SHOULD YOU EXPECT, THAT YOUR PERSONAL INFORMATION AND PRIVATE COMMUNICATIONS WILL ALWAYS REMAIN PRIVATE.</p>
    </div>
</div>